[engine_data]
textures_path = "res/textures/info.json"
input_config_path = "res/input_config.toml"

[engine_data.thread_pool]
threads_count = 0
queue_size = 0

[engine_data.state_machine]
process_levels = 1

[engine_data.script_engine]
is_start_script_engine = false

[engine_data.window]
title = "Alone World"
width = 900
height = 600

[shared_data]
