[engine_data]
textures_path = "res/textures/info.json"
input_config_path = "res/input_config.toml"

[engine_data.thread_pool]
threads_count = 0
queue_size = 0

[engine_data.script_engine]
is_start_script_engine = false

[shared_data]
